### ISSUE TITLE
dependency on python 2.6+ json module

### ISSUE THREAD

**Issue by RobertoMaurizzi** [andrefsp/pyflot#1]
Hi, I've tried to run pyflot in a python2.5 interpreter, and i found out that replacing json with simplejson (available on 2.5) is enough to make it work, at least with the chart types I'm using.

I know very little about the json modules, so I was wondering if I can expect problems if I try more complex charts or if on the other hand this change can be used to make your official version compatible with 2.5

Thanks for your work,

Roberto

**Comment by andrefsp** [comment]
Hi, first of all thanks for point that out. 

Well, this module its still in development and currently there is no official version for it and its not pypi yet. The idea behind this module its only to have a simple way to print graphs on a website through python to avoid the(in my opinion) painful javascript. 

Currently this library supports multi series plotting on the same graph, Linear and Time Series and also supports some of  the extra plot options provided by flot. 
Unfortunately I didn't write yet more examples but the existing one should be a good example on how this library should be used when plotting on HTML. 

You can also try to look in the tests, that might help you to have an overall idea of the current development status. 

My apologies for the bad documentation but you can expect better within a couple of months time. 

Best Regards

**Comment by RobertoMaurizzi** [comment]
The main advantage of your package is that you don't have to do the "guessing game" on how to put together all the data elements in the correct way: the code you write on the server is much more understandable and maintainable :-)
My only problem right now is with that 2.6+ python dependency, but only because I'm stuck with an old Debian server
